SLUG: # REQUIRED: machine friendly name of alias, must only contain characters `a-z`,`0-9`,`_`,`-`
  type: # [dictionary] REQUIRED: should always be `alias`
  name: # [string] REQUIRED: human friendly name. max 72 characters.
  description: # [string] OPTIONAL: human friendly description. max 270 characters.
  notes: # [string] OPTIONAL: designed for more developer friendly notes that do not suit the description field.
  file: # [path to file from repository root] REQUIRED: the path to the alias file that should be used. Must be of type csv.
  created: # [date] REQUIRED: YYYY-MM-DD of creation time.
  modified: # [date] REQUIRED: YYYY-MM-DD of creation time.
  created_by: # [string] REQUIRED: name of author , must only contain characters `a-z`,`0-9`,`_`,`-`
  version: # [number] REQUIRED: version number in format N.N.N
  test_cases: # [test extraction slug] REQUIRED: test cases for this extraction. Slugs found in extractions/test_cases/test_data.yaml