# ====== WHITELISTS =====

####### Examples #######

examples_whitelist:
  type: whitelist
  name: 'Examples whitelist'
  description: ''
  notes: ''
  file: 'whitelists/examples.txt'
  created: 2020-01-01
  modified:  2020-01-01
  created_by: DOGESEC
  version: 1.0.0
  test_cases: whitelist_examples

####### Alexa Top 1000 #######

alexa_top_1000_domains:
  type: whitelist
  name: 'Alexa Top 1000'
  description: ''
  notes: ''
  file: 'whitelists/alexa_top_1000_domains.txt'
  created: 2020-01-01
  modified:  2020-01-01
  created_by: DOGESEC
  version: 1.0.0
  test_cases: whitelist_alexa_top_1000_domains

####### Security vendors #######

security_vendor_domains:
  type: whitelist
  name: 'Security Vendor Domains'
  description: 'Pulled from https://github.com/muchdogesec/awesome-threat-intel-blogs'
  notes: ''
  file: 'whitelists/security_vendor_domains.txt'
  created: 2020-01-01
  modified:  2020-01-01
  created_by: DOGESEC
  version: 1.0.0
  test_cases: whitelist_security_vendor_domains